// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: demogrpc/item_like.proto

package demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemLikesService_GetItemLikes_FullMethodName = "/demo.ItemLikesService/GetItemLikes"
)

// ItemLikesServiceClient is the client API for ItemLikesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemLikesServiceClient interface {
	GetItemLikes(ctx context.Context, in *GetItemLikesReq, opts ...grpc.CallOption) (*ItemLikesResp, error)
}

type itemLikesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemLikesServiceClient(cc grpc.ClientConnInterface) ItemLikesServiceClient {
	return &itemLikesServiceClient{cc}
}

func (c *itemLikesServiceClient) GetItemLikes(ctx context.Context, in *GetItemLikesReq, opts ...grpc.CallOption) (*ItemLikesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemLikesResp)
	err := c.cc.Invoke(ctx, ItemLikesService_GetItemLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemLikesServiceServer is the server API for ItemLikesService service.
// All implementations should embed UnimplementedItemLikesServiceServer
// for forward compatibility.
type ItemLikesServiceServer interface {
	GetItemLikes(context.Context, *GetItemLikesReq) (*ItemLikesResp, error)
}

// UnimplementedItemLikesServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemLikesServiceServer struct{}

func (UnimplementedItemLikesServiceServer) GetItemLikes(context.Context, *GetItemLikesReq) (*ItemLikesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemLikes not implemented")
}
func (UnimplementedItemLikesServiceServer) testEmbeddedByValue() {}

// UnsafeItemLikesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemLikesServiceServer will
// result in compilation errors.
type UnsafeItemLikesServiceServer interface {
	mustEmbedUnimplementedItemLikesServiceServer()
}

func RegisterItemLikesServiceServer(s grpc.ServiceRegistrar, srv ItemLikesServiceServer) {
	// If the following call pancis, it indicates UnimplementedItemLikesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemLikesService_ServiceDesc, srv)
}

func _ItemLikesService_GetItemLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemLikesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemLikesServiceServer).GetItemLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemLikesService_GetItemLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemLikesServiceServer).GetItemLikes(ctx, req.(*GetItemLikesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemLikesService_ServiceDesc is the grpc.ServiceDesc for ItemLikesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemLikesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.ItemLikesService",
	HandlerType: (*ItemLikesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemLikes",
			Handler:    _ItemLikesService_GetItemLikes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demogrpc/item_like.proto",
}
